name: Regression Test
on:
  push:
    branches:
      - pipeline-sandbox

jobs:
  regression:
    runs-on: self-hosted
    steps:
      - name: Discover modified accelerators
        run: |
          cd $HOME/esp/utils/scripts/actions-pipeline
          ./get_modified_accelerators.sh
