name: Regression Test
on:
  push:
    branches:
      - pipeline-sandbox

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Run RTL simulations
        run: |
          cd $HOME/esp/utils/scripts/actions-pipeline
          ./run_sims.sh
      - name: Run esp-config
        run: |
          cd $HOME/esp/utils/scripts/actions-pipeline
          ./run_esp-config.sh
